### ISSUE TITLE
ColoredBoxGroup not respecting centerLabel bool value. 

### ISSUE THREAD

**Issue by David-Everlasting-Media** [Kurloc/ColoredBoxGroup#1]
Using at a root container. 
Example code. 
`[ColoredBoxGroup("Health", "Health Stats", .0f, .0f, .0f, 1f, true, true, true)]`

**Comment by MichaelTGood** [comment]
Yeah, I'm seeing the same thing as well.
`[ColoredBoxGroup("Control Components", 1,0,0,0.5f, true, true, true)]`

Otherwise, it's an awesome add-on! Thanks!

Unity 2021.1.18f1
Odin Inspector 3.0.8

**Comment by Kurloc** [comment]
Hey sorry I missed this original issue when it was added, thank you for adding the comment because the email caught my attention this morning! 

I'll take a look at it and push a fix.

**Comment by MichaelTGood** [comment]
I actually figured out the problem quickly by taking a look at it myself. I think you simply forgot to implement the "Center" feature. (Haha)

I throw in a simple IF statement, as well as a MarginTop and MarginBottom feature, like Schwapo's ColoredFoldoutGroup has. If you'd like, I can put these files together and send you a Pull Request. (again, not to imply I did any actual hard work.)

**Comment by MichaelTGood** [comment]
@Kurloc oh, and you can probably close this now. ;-)
