### ISSUE TITLE
Unity 2023.1.0b20 Crashes to desktop when using the ColoredBoxGroup tag

### ISSUE THREAD

**Issue by ziplock9000** [Kurloc/ColoredBoxGroup#4]
```
[ColoredBoxGroup("Colored Box Group Example",.76f, .23f, .64f, .98f,true, false, true)]
[TextAreaAttribute] public string description="Drink 10 beers in the nearest pub";
```

- The 2 source code files are in the root assets folder
- Odin 3.1.12.2 installed
- Odin's own BoxGroup works fine

**Comment by Kurloc** [comment]
Looking into this will try and repro today and push some fixes this week.

**Comment by ziplock9000** [comment]
As per request just now on Discord. This may or may not be related to my original post. All I can see from the logs is that Odin is the last known thing go be called.. so just a guess.

Now: U2023.1.5f1 Odin 3.1.14.1
[Editor.log](https://github.com/Kurloc/ColoredBoxGroup/files/12113908/Editor.log)

**Comment by Kurloc** [comment]
Looking into it now
